### ISSUE TITLE
Create base "spatial" structure with 3 matrices of the same size

### ISSUE THREAD

**Issue by lbarleta** [EMmobility/backlands#1]
* use a matrix with resolution 1,500 X 800

- status matrix, indicating the status of a particular plot of land:
1 = available (green)
2 = currently under use
3 = exhausted/resting
4 = urban area
9 = not usuable

- countdown matrix, indicating the number of 'ticks' for the change of status. Set False for those that were not dynamic (status 1, 4, and 9). Countdown periods (have as parameters):
for 2 => 3: randomized between 3~5 ticks
for 3 => 1: randomized between 20~40 ticks

- occupant: placeholder for now

**Comment by isabdr** [comment]
Done! I just need to figure it out how to create people and make them move around.
[Leo's Simulation.ipynb.zip](https://github.com/EMmobility/backlands/files/3159211/Leo.s.Simulation.ipynb.zip)
