### ISSUE TITLE
Transform status matrix into a img

### ISSUE THREAD

**Issue by lbarleta** [EMmobility/backlands#5]
E.g.: https://gist.github.com/lbarleta/61be0b67ed38252d878634a34eb8fee1

**Comment by isabdr** [comment]
Done!!

![picasion com_624dcad8a0cf30a42df0bc5d188e10c0](https://user-images.githubusercontent.com/49660578/57541825-c4c7c280-7304-11e9-81b4-484bec530e74.gif)

[Leo's Simulation (1).ipynb.zip](https://github.com/EMmobility/backlands/files/3167322/Leo.s.Simulation.1.ipynb.zip)

**Comment by lbarleta** [comment]
Awesome!
